---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache: yarn

script:
  - yarn lint:js
  - yarn lint:blueprints
  - yarn test

# We build PRs, but don't trigger separate builds for the PR from the branch.
branches:
  only:
    - master
